version: 2
jobs:
  build:
    branches:
      only:
        - master
    working_directory: /go/src/github.com/elko-dev/spawn
    docker:
      - image: larse514/circleci-golang:latest
    environment:
      TEST_RESULTS: /tmp/test-results

    steps:
    - checkout
    - run: mkdir -p $TEST_RESULTS

    - restore_cache:
        keys:
          - v1-pkg-cache
    - run: make -B
    - run:
        name: Release Binary
        command: |
          make publish-release
    - save_cache:
        key: v1-pkg-cache
        paths:
          - "/go/pkg"

    - store_artifacts:
        path: /tmp/test-results
        destination: raw-test-output

    - store_test_results:
        path: /tmp/test-results

        #${CIRCLE_BUILD_NUM}