// Code generated by MockGen. DO NOT EDIT.
// Source: applicationtype/applicationtypefactory.go

// Package applicationtype is a generated GoMock package.
package applicationtype

import (
	gomock "github.com/golang/mock/gomock"
	reflect "reflect"
)

// MockPrompt is a mock of Prompt interface
type MockPrompt struct {
	ctrl     *gomock.Controller
	recorder *MockPromptMockRecorder
}

// MockPromptMockRecorder is the mock recorder for MockPrompt
type MockPromptMockRecorder struct {
	mock *MockPrompt
}

// NewMockPrompt creates a new mock instance
func NewMockPrompt(ctrl *gomock.Controller) *MockPrompt {
	mock := &MockPrompt{ctrl: ctrl}
	mock.recorder = &MockPromptMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockPrompt) EXPECT() *MockPromptMockRecorder {
	return m.recorder
}

// ForType mocks base method
func (m *MockPrompt) ForType() (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ForType")
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ForType indicates an expected call of ForType
func (mr *MockPromptMockRecorder) ForType() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ForType", reflect.TypeOf((*MockPrompt)(nil).ForType))
}

// MockApplicationType is a mock of ApplicationType interface
type MockApplicationType struct {
	ctrl     *gomock.Controller
	recorder *MockApplicationTypeMockRecorder
}

// MockApplicationTypeMockRecorder is the mock recorder for MockApplicationType
type MockApplicationTypeMockRecorder struct {
	mock *MockApplicationType
}

// NewMockApplicationType creates a new mock instance
func NewMockApplicationType(ctrl *gomock.Controller) *MockApplicationType {
	mock := &MockApplicationType{ctrl: ctrl}
	mock.recorder = &MockApplicationTypeMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockApplicationType) EXPECT() *MockApplicationTypeMockRecorder {
	return m.recorder
}

// Create mocks base method
func (m *MockApplicationType) Create() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create")
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create
func (mr *MockApplicationTypeMockRecorder) Create() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockApplicationType)(nil).Create))
}

// MockWebTypeFactory is a mock of WebTypeFactory interface
type MockWebTypeFactory struct {
	ctrl     *gomock.Controller
	recorder *MockWebTypeFactoryMockRecorder
}

// MockWebTypeFactoryMockRecorder is the mock recorder for MockWebTypeFactory
type MockWebTypeFactoryMockRecorder struct {
	mock *MockWebTypeFactory
}

// NewMockWebTypeFactory creates a new mock instance
func NewMockWebTypeFactory(ctrl *gomock.Controller) *MockWebTypeFactory {
	mock := &MockWebTypeFactory{ctrl: ctrl}
	mock.recorder = &MockWebTypeFactoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockWebTypeFactory) EXPECT() *MockWebTypeFactoryMockRecorder {
	return m.recorder
}

// Create mocks base method
func (m *MockWebTypeFactory) Create(applicationType string) (ApplicationType, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", applicationType)
	ret0, _ := ret[0].(ApplicationType)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create
func (mr *MockWebTypeFactoryMockRecorder) Create(applicationType interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockWebTypeFactory)(nil).Create), applicationType)
}

// MockMobileTypeFactory is a mock of MobileTypeFactory interface
type MockMobileTypeFactory struct {
	ctrl     *gomock.Controller
	recorder *MockMobileTypeFactoryMockRecorder
}

// MockMobileTypeFactoryMockRecorder is the mock recorder for MockMobileTypeFactory
type MockMobileTypeFactoryMockRecorder struct {
	mock *MockMobileTypeFactory
}

// NewMockMobileTypeFactory creates a new mock instance
func NewMockMobileTypeFactory(ctrl *gomock.Controller) *MockMobileTypeFactory {
	mock := &MockMobileTypeFactory{ctrl: ctrl}
	mock.recorder = &MockMobileTypeFactoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockMobileTypeFactory) EXPECT() *MockMobileTypeFactoryMockRecorder {
	return m.recorder
}

// Create mocks base method
func (m *MockMobileTypeFactory) Create(applicationType string) (ApplicationType, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", applicationType)
	ret0, _ := ret[0].(ApplicationType)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create
func (mr *MockMobileTypeFactoryMockRecorder) Create(applicationType interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockMobileTypeFactory)(nil).Create), applicationType)
}

// MockFunctionTypeFactory is a mock of FunctionTypeFactory interface
type MockFunctionTypeFactory struct {
	ctrl     *gomock.Controller
	recorder *MockFunctionTypeFactoryMockRecorder
}

// MockFunctionTypeFactoryMockRecorder is the mock recorder for MockFunctionTypeFactory
type MockFunctionTypeFactoryMockRecorder struct {
	mock *MockFunctionTypeFactory
}

// NewMockFunctionTypeFactory creates a new mock instance
func NewMockFunctionTypeFactory(ctrl *gomock.Controller) *MockFunctionTypeFactory {
	mock := &MockFunctionTypeFactory{ctrl: ctrl}
	mock.recorder = &MockFunctionTypeFactoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockFunctionTypeFactory) EXPECT() *MockFunctionTypeFactoryMockRecorder {
	return m.recorder
}

// Create mocks base method
func (m *MockFunctionTypeFactory) Create(applicationType string) (ApplicationType, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", applicationType)
	ret0, _ := ret[0].(ApplicationType)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create
func (mr *MockFunctionTypeFactoryMockRecorder) Create(applicationType interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockFunctionTypeFactory)(nil).Create), applicationType)
}

// MockAPITypeFactory is a mock of APITypeFactory interface
type MockAPITypeFactory struct {
	ctrl     *gomock.Controller
	recorder *MockAPITypeFactoryMockRecorder
}

// MockAPITypeFactoryMockRecorder is the mock recorder for MockAPITypeFactory
type MockAPITypeFactoryMockRecorder struct {
	mock *MockAPITypeFactory
}

// NewMockAPITypeFactory creates a new mock instance
func NewMockAPITypeFactory(ctrl *gomock.Controller) *MockAPITypeFactory {
	mock := &MockAPITypeFactory{ctrl: ctrl}
	mock.recorder = &MockAPITypeFactoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockAPITypeFactory) EXPECT() *MockAPITypeFactoryMockRecorder {
	return m.recorder
}

// Create mocks base method
func (m *MockAPITypeFactory) Create(applicationType string) (ApplicationType, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", applicationType)
	ret0, _ := ret[0].(ApplicationType)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create
func (mr *MockAPITypeFactoryMockRecorder) Create(applicationType interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockAPITypeFactory)(nil).Create), applicationType)
}
