// Code generated by MockGen. DO NOT EDIT.
// Source: applicationtype/applicationtypefactory.go

// Package applicationtype is a generated GoMock package.
package applicationtype

import (
	prompt "github.com/elko-dev/spawn/prompt"
	web "github.com/elko-dev/spawn/web"
	gomock "github.com/golang/mock/gomock"
	reflect "reflect"
)

// MockPrompt is a mock of Prompt interface
type MockPrompt struct {
	ctrl     *gomock.Controller
	recorder *MockPromptMockRecorder
}

// MockPromptMockRecorder is the mock recorder for MockPrompt
type MockPromptMockRecorder struct {
	mock *MockPrompt
}

// NewMockPrompt creates a new mock instance
func NewMockPrompt(ctrl *gomock.Controller) *MockPrompt {
	mock := &MockPrompt{ctrl: ctrl}
	mock.recorder = &MockPromptMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockPrompt) EXPECT() *MockPromptMockRecorder {
	return m.recorder
}

// ForType mocks base method
func (m *MockPrompt) ForType() (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ForType")
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ForType indicates an expected call of ForType
func (mr *MockPromptMockRecorder) ForType() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ForType", reflect.TypeOf((*MockPrompt)(nil).ForType))
}

// MockTempAppType is a mock of TempAppType interface
type MockTempAppType struct {
	ctrl     *gomock.Controller
	recorder *MockTempAppTypeMockRecorder
}

// MockTempAppTypeMockRecorder is the mock recorder for MockTempAppType
type MockTempAppTypeMockRecorder struct {
	mock *MockTempAppType
}

// NewMockTempAppType creates a new mock instance
func NewMockTempAppType(ctrl *gomock.Controller) *MockTempAppType {
	mock := &MockTempAppType{ctrl: ctrl}
	mock.recorder = &MockTempAppTypeMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockTempAppType) EXPECT() *MockTempAppTypeMockRecorder {
	return m.recorder
}

// Create mocks base method
func (m *MockTempAppType) Create(action web.SpawnAction, userCommands prompt.UserSelections) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", action, userCommands)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create
func (mr *MockTempAppTypeMockRecorder) Create(action, userCommands interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockTempAppType)(nil).Create), action, userCommands)
}
